worker_processes 1;

error_log /home/s1157115/error.log;
pid /home/s1157115/nginx.pid;

events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	server {
		listen 17115;
		server_name s1157115.student.inf.st.hsleiden.nl;
		access_log /home/s1157115/access.log;

		location / {
			root /home/s1157115/frontend;
			try_files $uri $uri/ /index.html;
		}
	}
}
